### PR TITLE
Add Attribute Key Variable and Drafts Support

### PR DESCRIPTION
**Pull request by bnice5000**
Added the ability to handle attribute keys other than class. Also added the ability to handle drafts and hidden pages.

Changed the pelicanconf.py to an opt in model. Added the ability to turn on and off bootstrap table and bootstrap img class attributes.

### CODE REVIEW

**Comment by ingwinlu** [comment]
Hi,

thanks for your work on this. I have a few questions/feedback:
* I would like to keep a single configuration line as I do not see an advantage of using multiple ones. This would cut down the code and documentation considerably, hence it is easier to use / modify in the future
* related to above, why are the defaults set on each run of bootstrapify and not in the initialization part of the plugin?
* is the `unicode_literals` import necessary or can it be avoided?
* ` +  logger.debug('Has dict, {0}, {1}, {2}'.format(selector, attribute_key, attribute_value))` either replace with a more describing text or remove completely

**Comment by bnice5000** [comment]
In response your comments:

 - The default with pelican plugins seems to be that just adding the plugin does not initialize the feature set. There needs to be an additional opt in the configuration to initialize the feature set. I was trying to maintain alignment with the current trends in plugins methodology. If I was to guess why, it is because it is easier to comment out a line in the configuration file than an item in a list. Also, I set it up so that it is only one additional option to turn everything on. I like having more control over the configuration. I am not sure everyone needs both table and img support. The additional settings allow those to be set and minimizes unnecessary iterations over their pages and articles. Additionally, Bootstrap 4 adds a lot of new bootstrap elements that could be added to this file and it might become ungainly to not allow people the pick and choose what items they would like turned on.
- As far as I can tell, it does not make a runtime difference, based on the way the signal system operates, where these lines are placed. It was a programming choice. I placed those lines closer to the code I was working on and it resulted in less scrolling.
- Python 3 future proofing. See https://docs.python.org/2/howto/pyporting.html
- It looks like I forgot to remove a debug message. This one specifically was about making sure I maintained backward compatibility with the original style of dictionaries with/without a sub-dictionary. Feel free to remove it or change it as you see fit.

**Comment by ingwinlu** [comment]
I do not like the multiple settings. It makes the code as well as the effect of the plugin more abstruse. If you can remove those and remove the then unnecessary initialization of the dict I will happily merge this contribution.

**Comment by bnice5000** [comment]
I'll pass. You are welcome to use and or modify to code if you like. Sorry to have bothered you.

**Comment by ingwinlu** [comment]
no bother at all, the added functionality would have been nice.

**Pull request closed without merging**
